import type { Metadata } from "next";
import './ui/css/globals.css'


export const metadata: Metadata = {
  title: "TO-DO APP | Luca Ramirez",
  description: "Generated by create next app",
};

import StoreProvider from "./StoreProvider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
